### ISSUE TITLE
Add option to set AWS_STS_REGIONAL_ENDPOINTS variable

### ISSUE THREAD

**Issue by lanzrein** [coder/enterprise-helm#213]
Hello, 

Currently when using ECR images with coder and using IRSA, the coderd will authenticate with sts.amazonaws.com. 
However in some settings, such as a VPC without an internet gateway we do not always have access to this URL. For these purposes, we use the regional endpoint which would be enabled with a VPC endpoint. For instance in eu-west-1 sts.eu-west-1.amazonaws.com. 

Using the reigonal endpoint is done automatically by adding a environment variable `AWS_STS_REGIONAL_ENDPOINTS=regional` in the env attributes of coderd. 

For instance, we could have a value `coderd.awsStsRegionalEndpoints` and then in the `coderd.yaml` file add the following in the `env` sections: 

```yaml
            {{- if .Values.coderd.awsStsRegionalEndpoints }}
             - name : AWS_STS_REGIONAL_ENDPOINTS
                value : "regional"
            {{- end }}
```

I have already tested by manually adding the environment variable in the deployment on an existing configuration and can confirm that it resolves the issue. 

We could set the value `awsStsRegionalEndpoints` to `false` by default to ensure retro-compatibility. 
Is this something you could implement ? 

I could also open an MR if you want.
