### ISSUE TITLE
Ingress Dev Url bugs and fixes

### ISSUE THREAD

**Issue by stevek-pro** [coder/enterprise-helm#231]
A quick helm dry run gives me:

```
  rules:
  - host: "coder.theDomain.io"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: coderd
            port:
              name: tcp-coderd
  - host: "*.theDomain.io"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: coderd
            port:
              name: tcp-coderd
  tls:
    - hosts:
      - "code.theDomain.io"
      secretName: "coder-theDomain-io-tls"
```

In above snippet I would have expected the wildcard tls host entry to get created as well. When I look in [Ingress](https://github.com/coder/enterprise-helm/blob/main/templates/ingress.yaml) template  I found these ambiguities:

**Line 40:** `.Values.coderd.devurlsHost`
**Line 57:** `.Values.devurls`

Next, in the Docs it is written that one needs to create a **seperate ingress** manually. An own ingress will most likely conflict. I think this is a Documentation bug/ambiguity and should be adressed.

Next, there is no option to set ingress classname. 

See my Pull Requests adressing a few of these issues:
PR https://github.com/coder/enterprise-helm/pull/232 created. 
PR https://github.com/coder/enterprise-helm/pull/233 created.
